### ISSUE TITLE
iframe with run results not yet ideal

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/tests#32]
The iframe for the results contains a black border (on by default) that can be removed by adding a `border: 0` style to it.

The iframe for the results somehow makes content a bit too wide eg cutting of the table for me (and making it hard to scroll): 
![image](https://user-images.githubusercontent.com/226374/205135311-bfc1389a-b56b-4ab8-bb38-e036b9b4debd.png)

This is probably some `margin` or `padding` setting either on the iframe or on the html/body/blah tags on the inside page.

The iframe does not exent to the very right of the window so if a the scrollbar is visible there is a visible gap, it also makes scrolling harder: 
![image](https://user-images.githubusercontent.com/226374/205135711-ebdbc560-030e-4b66-ac81-4a25f5317372.png)

**Comment by nadinekuo** [comment]
Idea: add padding to body of iframe
