### ISSUE TITLE
CI badge broken on some pages

### ISSUE THREAD

**Issue by Sbozzolo** [EinsteinToolkit/tests#44]
Hello,

I think that the badge does not show correctly on some pages of the website,
see
![2022-12-12:11:25:39](https://user-images.githubusercontent.com/9167485/207124970-b0623286-bede-4aa8-86d1-14153b4156d0.png)
The linked image is https://www.einsteintoolkit.org/documentation/images/pending-status.svg, which is different from the one that I see on the main page (right now the image link on the homepage is https://github.com/EinsteinToolkit/tests/actions/runs/3678184035)

**Comment by nadinekuo** [comment]
Could you give an example of a specific page on which this occurs? I cannot seem to recreate this

**Comment by Sbozzolo** [comment]
I included one in the screenshot above:

http://einsteintoolkit.org/about/releases/ET_2022_11_announcement.html

But also
http://einsteintoolkit.org/documentation/ThornGuide.php for example.

**Comment by rhaas80** [comment]
Still/? I thought I fixed those already. @nadinekuo the fix I applied is in menus.js and you need to change like in cf85d2c

**Comment by nadinekuo** [comment]
Thanks!
