### ISSUE TITLE
no link to test log in build 600

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/tests#51]
https://test.einsteintoolkit.org/build_600.html reports a failure in NRPyEllipticET and a test log file exists in github at https://github.com/EinsteinToolkit/tests/blob/gh-pages/records/version_600/sim_600_1/NRPyEllipticET/NRPyEllipticET_test_conformally_flat_BBH.log but no link is being provided.

**Comment by Hrishikesh-Kalyanaraman** [comment]
resolved
