### ISSUE TITLE
failed tests email not sent for build 600

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/tests#53]
Built 600 was a failure [http://test.einsteintoolkit.org/build_600.html](http://test.einsteintoolkit.org/build_600.html) but no email about a test failure was sent to test@einsteintoolkit.org: [http://lists.einsteintoolkit.org/pipermail/test/](http://lists.einsteintoolkit.org/pipermail/test/)

This could be a failure in the testing code or on the mailing list server. In either case it should be fixed.

**Comment by rhaas80** [comment]
Looking at the action log https://github.com/EinsteinToolkit/tests/actions/runs/4198787292/jobs/7282863819 I see:

```
usage: mail.py [-h] [--master MASTER] --ghpages GHPAGES 
mail.py: error: the following arguments are required: --ghpages
```

**Comment by Hrishikesh-Kalyanaraman** [comment]
resolved
