### ISSUE TITLE
running out of disk space for runner

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/tests#57]
The runner is using too much disk space (likely gh-pages which is about 18GB for me):

![image](https://user-images.githubusercontent.com/226374/220999950-91e22cef-cf13-4aec-9b41-3202bde6e530.png)

One can likely explore a shallow checkout for gh-pages (and also make sure that all checkouts are truely single branch).

**Comment by Hrishikesh-Kalyanaraman** [comment]
fixed. Added single branch for master, and latest commit for scripts and gh-pages
