### ISSUE TITLE
use life display of workflow state

### ISSUE THREAD

**Issue by rhaas80** [EinsteinToolkit/tests#6]
The workflow API endpoint https://api.github.com/repos/rhaas80/einsteintoolkit/actions/workflows/main.yml/runs documented here https://docs.github.com/rest/reference/actions#list-workflow-runs seems to show the "life" state of workflows.

**Comment by nadinekuo** [comment]
https://api.github.com/repos/EinsteinToolkit/tests/actions/runs

**Comment by nadinekuo** [comment]
See https://github.com/rhaas80/last-successful-commit-action/blob/master/dist/index.js for an example on how to fetch workflow API

**Comment by nadinekuo** [comment]
Seems like these are the status values: 
![image](https://user-images.githubusercontent.com/74115586/201787170-1530e025-f0aa-40bd-9dba-c17ef3b4005a.png)

From https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch

**Comment by rhaas80** [comment]
Like so:
```
var membersFile = new XMLHttpRequest();
undefined
membersFile.open("GET", "https://api.github.com/repos/rhaas80/einsteintoolkit/actions/workflows/main.yml/runs");
undefined
membersFile.send();
undefined
XHRGEThttps://api.github.com/repos/rhaas80/einsteintoolkit/actions/workflows/main.yml/runs
[HTTP/2 200 OK 1234ms]

membersFile.responseTex;
undefined
obj = JSON.parse(membersFile.responseText);
Object { total_count: 47, workflow_runs: (30) […] }

obj.workflow_runs[0].conclusion 
```
